name: Post Image to Bluesky

on:
  schedule:
    - cron: '0 10 * * 1'  # Executa toda segunda-feira às 7am BRT (UTC-3), ajustado para UTC
  workflow_dispatch:  # Permite a execução manual do workflow

jobs:
  post-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Ou a versão que seu projeto requer

    - name: Install dependencies
      run: npm install  # Instala as dependências do projeto

    - name: Run index.ts
      run: npm run post-next-image  # Executa o script que você configurou
      env:
        BSKY_IDENTIFIER: ${{ secrets.BSKY_IDENTIFIER }}  # Seu identificador da Bluesky
        BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}  # Sua senha da Bluesky
        REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}  # Token de acesso ao repositório

      - uses: action-pack/set-variable@v1
        with:
          name: 'LAST_IMAGE_NAME'
          value: ${{ env.NEW_LAST_IMAGE_NAME }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
